language: python
dist: trusty
sudo: required
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pydes
script:
  - "export PYTHONPATH=$PYTHONPATH:."
  - "sudo python PythonLearnA.py"